import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const suiteFont = localFont({
  src: [
    {
      path: "/assets/fonts/SUITE-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-suite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={suiteFont.variable}>
      <body className={suiteFont.className}>{children}</body>
    </html>
  );
}
